# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c1226ea60d2fd26a3be2a73799b33075b4248741056a6bbb4297ed21669147001c6728b4d18dac524ffbbb55675e52122a3a15c8a52b7d5699d4229a6963a8b

test:
  secret_key_base: 6c3f8e293cc843bf895bebcd02b9d37327942a740607b128f3ce5a5367689c8df6db477311d97e5e0b338e7b80947a2153461d02122edac8a8f1d1790665e822

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
